/*
 * Copyright 2026 Google LLC
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

package com.google.adk.kt.types

import kotlinx.serialization.Serializable

/** The reason why the generation finished. */
@Serializable
enum class FinishReason {
  /** The finish reason is unspecified. */
  FINISH_REASON_UNSPECIFIED,

  /** Token generation reached a natural stopping point or a configured stop sequence. */
  STOP,

  /** Token generation reached the configured maximum output tokens. */
  MAX_TOKENS,

  /**
   * Token generation stopped because the content potentially contains safety violations. NOTE: When
   * streaming, [content][] is empty if content filters blocks the output.
   */
  SAFETY,

  /** The token generation stopped because of potential recitation. */
  RECITATION,

  /** All other reasons that stopped the token generation. */
  OTHER,

  /** Token generation stopped because the content contains forbidden terms. */
  BLOCKLIST,

  /** Token generation stopped for potentially containing prohibited content. */
  PROHIBITED_CONTENT,

  /**
   * Token generation stopped because the content potentially contains Sensitive Personally
   * Identifiable Information (SPII).
   */
  SPII,

  /** The function call generated by the model is invalid. */
  MALFORMED_FUNCTION_CALL,

  /** A tool returned an unexpected result, or a tool threw an exception. */
  UNEXPECTED_TOOL_CALL,
}
